name: frontend-bootcamp-cicd

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  APP_ID: dicxwv2f5ex1s
  BRANCH_NAME: master
  BUCKET_S3: frontend-bootcamp


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - name: build frontend
      run: |
          npm run build
    - name: ZIP Frontend
      run: cd build;zip ../dist.zip * -r  

    - uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: dist.zip     

  deploy:
    runs-on: ubuntu-latest  
    needs: [build]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    
    steps:
    - uses: actions/checkout@v3
    
    - uses: actions/download-artifact@v3
      with:
        name: node-app
 
    - name: upload bucket-s3
      run: aws s3 cp dist.zip s3://${{ env.BUCKET_S3 }}

    - name: deploy AWS Amplify
      run: aws amplify start-deployment --app-id ${{ env.APP_ID }} --source-url s3://${{ env.BUCKET_S3 }}/dist.zip --branch-name ${{ env.BRANCH_NAME }}


   
